// <auto-generated />
using System;
using CofFeeShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CofFeeShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CofFeeShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Strong Coffees"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Medium Blend Coffees"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Seasonal Coffees"
                        });
                });

            modelBuilder.Entity("CofFeeShop.Models.Coffee", b =>
                {
                    b.Property<int>("CoffeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCoffeeOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CoffeeId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Coffees");

                    b.HasData(
                        new
                        {
                            CoffeeId = 1,
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            InStock = true,
                            IsCoffeeOfTheWeek = true,
                            LongDescription = "Our Home Blend has a medium body which is complemented by deep red fruit acidity, cocoa sweetness and a pleasant lingering finish.",
                            Name = "Home Blend Coffee",
                            Price = 12.95m,
                            ShortDescription = "Award-Winning Home Blend Coffee"
                        },
                        new
                        {
                            CoffeeId = 2,
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/blueberrycheesecakesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/blueberrycheesecake.jpg",
                            InStock = true,
                            IsCoffeeOfTheWeek = true,
                            LongDescription = "an aroma of sweet caramel",
                            Name = "Red Blend Coffee",
                            Price = 18.95m,
                            ShortDescription = "little bit of luxury!"
                        },
                        new
                        {
                            CoffeeId = 3,
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cheesecakesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cheesecake.jpg",
                            InStock = true,
                            IsCoffeeOfTheWeek = false,
                            LongDescription = "a really strong coffee with lots of body and flavour.",
                            Name = "Colombian",
                            Price = 18.95m,
                            ShortDescription = "Pure blend"
                        },
                        new
                        {
                            CoffeeId = 4,
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cherrypiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cherrypie.jpg",
                            InStock = true,
                            IsCoffeeOfTheWeek = false,
                            LongDescription = "If you like flavoured coffe this is for you",
                            Name = "HazelNut Coffee",
                            Price = 15.95m,
                            ShortDescription = "Delicious and tasty Hazelnut"
                        },
                        new
                        {
                            CoffeeId = 5,
                            CategoryId = 3,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasapplepiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasapplepie.jpg",
                            InStock = true,
                            IsCoffeeOfTheWeek = false,
                            LongDescription = "A natural processed coffee whilst avoiding any negative over-fermented notes",
                            Name = "Natural BURUI",
                            Price = 13.95m,
                            ShortDescription = "A natural processed coffee"
                        },
                        new
                        {
                            CoffeeId = 6,
                            CategoryId = 3,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberrypiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberrypie.jpg",
                            InStock = true,
                            IsCoffeeOfTheWeek = false,
                            LongDescription = "fudge-like sweetness and chocolate notes.",
                            Name = "Flora",
                            Price = 17.95m,
                            ShortDescription = "perfect for winter days"
                        },
                        new
                        {
                            CoffeeId = 7,
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/peachpiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/peachpie.jpg",
                            InStock = false,
                            IsCoffeeOfTheWeek = false,
                            LongDescription = "a long fermentation process that ramps up both the fruity characteristics",
                            Name = "Grace",
                            Price = 15.95m,
                            ShortDescription = "a coffee that really stand out"
                        },
                        new
                        {
                            CoffeeId = 8,
                            CategoryId = 3,
                            ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinpiesmall.jpg",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinpie.jpg",
                            InStock = true,
                            IsCoffeeOfTheWeek = true,
                            LongDescription = "The coffee is rounded with milk chocolate notes.",
                            Name = "Vista",
                            Price = 12.95m,
                            ShortDescription = "a mix of bourbon varieties"
                        });
                });

            modelBuilder.Entity("CofFeeShop.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("CoffeeId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("CoffeeId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("CofFeeShop.Models.Coffee", b =>
                {
                    b.HasOne("CofFeeShop.Models.Category", "Category")
                        .WithMany("Coffees")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CofFeeShop.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("CofFeeShop.Models.Coffee", "Coffee")
                        .WithMany()
                        .HasForeignKey("CoffeeId");

                    b.Navigation("Coffee");
                });

            modelBuilder.Entity("CofFeeShop.Models.Category", b =>
                {
                    b.Navigation("Coffees");
                });
#pragma warning restore 612, 618
        }
    }
}
